### PR TITLE
Profiles configuration without symbolic links

### PR DESCRIPTION
**Pull request by SlimaneAmar**
Signed-off-by: Slimane AMAR <slimane.amar@rte-france.com>

### CODE REVIEW

**Comment by jonenst** [comment]
This brings back the behavior of create containers and network with a prefix of "docker-compose":
```
$ docker-compose up
Creating network "docker-compose_default" with the default driver
```

With the symlinks it worked:
```
$ docker-compose up
Creating network "study_default" with the default driver
```

Need to set the COMPOSE_PROJECT_NAME in .env files

**Comment by geofjamg** [comment]
> This brings back the behavior of create containers and network with a prefix of "docker-compose":
> 
> ```
> $ docker-compose up
> Creating network "docker-compose_default" with the default driver
> ```
> 
> With the symlinks it worked:
> 
> ```
> $ docker-compose up
> Creating network "study_default" with the default driver
> ```
> 
> Need to set the COMPOSE_PROJECT_NAME in .env files

Why would we need to do that?

**Comment by jonenst** [comment]
To have containers named after the project.

Not sure about having all our containers named "grid_something" and shared between profiles, vs having different containers for the different profiles (gridstudy_case_server and gridmerge_case_server)

**Comment by SlimaneAmar** [comment]
For the name (default driver et containers), is it better to put the name of the directory (all, study, merging) or something else (gridall, gridstudy, gridmerge, ...)

**Comment by jonenst** [comment]
"all" is a bad name (just like the previous "docker-compose")

**Comment by SlimaneAmar** [comment]
and for the others profiles ?

**Review by jonenst — APPROVED** [review]

**Pull request merged**
